[package]
name = "pe-parser"
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["Isaac Marovitz <isaacmarovitz@gmail.com>"]
description = "A blazing fast PE Parser with pretty print"
readme = "README.md"
repository = "https://github.com/IsaacMarovitz/pe-parser"
keywords = ["parser", "cli", "windows", "binary"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = {version = "1.13.1", features = ["derive"]}
num-traits = "0.2"
num-derive = "0.2"
bitflags = "2.1.0"
chrono = "0.4.24"
clap = { version = "4.2.4", features = ["cargo"] }
datatest-stable = "0.1.3"

[[test]]
name = "pe-parser"
harness = false
