[package]
name = "pe-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = {version = "1.13.1", features = ["derive"]}
num-traits = "0.2"
num-derive = "0.2"
bitflags = "2.1.0"