name: Fuzz

on:
 workflow_dispatch:
 schedule:
  - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Fuzz
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Install fuzz
      run: cargo install cargo-fuzz
    
    - name: Run fuzzer
      run: cargo fuzz run pe-parser
