name: Fuzz

on:
 workflow_dispatch:
 schedule:
  - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Fuzz
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Fuzz
      run: cargo fuzz run pe-parser
